version: '3.8'

services:
  fastapi-app:
    build: .
    container_name: fastapi-app
    restart: always
    ports:
      - "8000:8000"
    command: >
      uvicorn main:app --host=0.0.0.0
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_USERNAME}

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  mysql-test:
    image: mysql:8.0
    container_name: mysql-test
    ports:
      - "13306:3306"
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_USERNAME}

  redis-test:
    image: redis:alpine
    container_name: redis-test
    ports:
      - "16379:6379"
